### ISSUE TITLE
Namespace pymdown options and settings under `pymdown`

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/PyMdown#45]
It has occurred to me if you are going to be previewing pymdown stuff that is run through other stuff as well, it may be smart to namespace the pymdown settings and options. Things like title doesn't have to be under `pymdown` though as it is something general used by other systems.

```yaml
pymdown:
  destination: some/path
  settings:
    somesetting: 3
```
